services:
  intent-engine:
    build: .
    container_name: intent_prediction_server
    restart: unless-stopped
    network_mode: host
    user: 1000:1000

    volumes:
      - /home/regd/AWARE/apr25/:/app/data/
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
    environment:
      - TASK_PRED__DATA_DIR=/app/data
      - TASK_PRED__NATS_HOST=nats://localhost:4222
      - TASK_PRED__SAMPLING_INTERVAL_MS=100

      # Parquet Sink Configuration
      - INTENT__PARQUET__ENABLED=true
      - INTENT__PARQUET__OUTPUT_DIR=/app/data/
      - INTENT__PARQUET__MAX_TIME_FLUSH_SEC=30

      - INTENT__NATS__ENABLED=true
      - INTENT__NATS__NATS__SUBJECT=intent.aircraft_attention_target

      # 
      - INTENT__TERMINAL__ENABLED=true
      
      # Logging
      - INTENT__LOGGING__LEVEL=DEBUG
    
volumes:
  data: