services:
  instance-pred:
    build: .
    container_name: instance-pred
    network_mode: host
    user: 1000:1000

    volumes:
      - ~/data/:/app/data/
    
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
    environment:
      - INTENT__DATA_DIR=/app/data
      - INTENT__NATS_HOST=nats://127.0.0.1:4222
      - INTENT__SAMPLING_INTERVAL_MS=100

      # Parquet Sink Configuration
      - INTENT__PARQUET__ENABLED=true
      - INTENT__PARQUET__MAX_TIME_FLUSH_SEC=30

      - INTENT__NATS__ENABLED=true
      - INTENT__NATS__NATS__SUBJECT=intent.aircraft_attention_target

      # 
      - INTENT__TERMINAL__ENABLED=true
      
      # Logging
      - INTENT__LOGGING__LEVEL=DEBUG