[project]
name = "instance-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "aware-protos",
    "fastapi>=0.128.0",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "pydantic-settings>=2.12.0",
    "rich>=14.3.2",
    "typer>=0.21.1",
    "uvicorn>=0.40.0",
    "zmq>=0.0.0",
]

[project.scripts]
instance-pred = "instance_pred.__main__:app"

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "aware-protos/python",
]

[tool.uv.sources]
aware-protos = { workspace = true }
